# Generated by Django 4.2.6 on 2024-05-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year_of_release',
            field=models.IntegerField(),
        ),
    ]
